select*from customer limit 20

--total revenue generated by male vs female
select gender,sum(purchase_amount) as revenue
from customer
group by gender

--which customer use discount still spend more than avg amt
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--which are the top 5 products with the highes average review rating 
select item_purchased, ROUND (AVG (review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5 ;

--compare the abg purchase amt between standaed and express shipping
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--do subscribed customers spend more? compare avg spend and total revenue between subscribers and non subscribers
select subscription_status ,
count(customer_id) as total_customer,
round (avg(purchase_amount),2) as avg_spend,
round (sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue , avg_spend desc;

--which 5 products have the heighest percentage of purchase with discounts applied ??
select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end) / count(*) , 2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc limit 5 ;

--segment cust. into new ,returning and loyal based on their total no. of previous purchases , and show the count of each segment. 
with customer_type as (
select customer_id , previous_purchases,
case 
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)

select customer_segment , count(*) as "no. of customers"
from customer_type
group by customer_segment